### ISSUE TITLE
Upgrading to v3.0.0 broke SSL auth

### ISSUE THREAD

**Issue by AmandaHassoun** [mdawar/rq-exporter#38]
I was seeing the following error:

```
redis.exceptions.ConnectionError: Error 1 connecting to <IP>:6378. [SSL: CERTIFICATE_VERIFY_FAILED] 
certificate verify failed: Missing Authority Key Identifier (_ssl.c:1020).
```
Connecting directly using `redis-cli` worked fine.

Pinning the version to `v2.1.2` fixed it.

**Comment by mdawar** [comment]
Thank you for reporting this issue.
 `v3.0.0` added support for `rq` `2.0` and updated the `redis` version to `v5.2.0`.

Can you please provide a minimal example to reproduce the error?
Are you using the Docker image?

**Comment by AmandaHassoun** [comment]
Thanks for the quick response!

> Can you please provide a minimal example to reproduce the error?

Below is the docker command we're using to run it:
```
docker run 
--restart unless-stopped 
-d 
-v /tmp/ssl.pem:/tmp/ssl.pem 
--name rq-prometheus-exporter 
-p 9726:9726
mdawar/rq-exporter:v2.1.2 \
--redis-url "rediss://:<auth string>@<redis host IP>:<redis host port>/0?ssl_ca_certs=/tmp/ssl.pem"
```

**Comment by mdawar** [comment]
I tried to replicate the error and I couldn't, this is what I tried.

Generated the certificates:
```sh
openssl req -x509 -newkey rsa:2048 -nodes -keyout redis.key -out redis.crt -days 365
cp redis.crt ca.crt
```

Used this Redis configuration:
```
bind 0.0.0.0
tls-port 6378
tls-cert-file /data/certs/redis.crt
tls-key-file /data/certs/redis.key
tls-ca-cert-file /data/certs/ca.crt
tls-auth-clients no
requirepass 123456
```

And this is the compose file:
```yml
services:
  redis:
    image: redis:7.4-alpine
    command:
      - redis-server
      - /etc/redis.conf
    ports:
      - 6379:6379
      - 6378:6378
    volumes:
      - ./redis.conf:/etc/redis.conf
      - ./certs:/data/certs

  rq_exporter:
    image: mdawar/rq-exporter:v3.0.0
    ports:
      - target: 9726
        published: 9726
        protocol: tcp
        mode: host
    environment:
      RQ_REDIS_URL: rediss://:123456@redis:6378/0?ssl_ca_certs=/tmp/ca.crt
    volumes:
      - ./certs:/tmp
    depends_on:
      - redis
```
